language: php
php:
  - 5.3
services:
  - mysql
before_script:
  - composer install --no-interaction --prefer-source # Have to prefer source or hit github rate limit
  - git submodule update --init --recursive
  - mkdir application/cache application/logs
  - chmod 777 application/cache application/logs
  # db setup
  - mysql -e 'create database pingapp_test;'
  - ./minion --task=migrations:run --up
  # webserver setup
  - php -S localhost:8000 httpdocs/index.php &
  - sleep 3

script:
  - ./bin/phpunit -c application/tests/phpunit.xml